name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: install swipl
      run: >
        sudo apt-add-repository ppa:swi-prolog/stable
        sudo apt-get update
        sudo apt-get install swi-prolog
    - uses: actions/checkout@v2
    - name: run tests
      run: swipl -t "run_tests(muggin)." muggin.pl
